#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
rm err
rm CdCl.log
rm pics/*.png

#rm -rf dynamicCode
#rm -rf constant/coarseMesh
#rm -f system/coarseMesh/decomposeParDict

#------------------------------------------------------------------------------
